// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, db DBTX, id string) (User, error)
	InsertAndReturnUser(ctx context.Context, db DBTX, arg InsertAndReturnUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
