// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Entity struct {
	ID          string         `json:"id"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	Email       string         `json:"email"`
	Phone       string         `json:"phone"`
	Status      string         `json:"status"`
	AssignedTo  sql.NullString `json:"assigned_to"`
	CreatedAt   string         `json:"created_at"`
	ConvertedAt string         `json:"converted_at"`
}

type Task struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	DueDate     string         `json:"due_date"`
	AssignedTo  sql.NullString `json:"assigned_to"`
	Status      string         `json:"status"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
}
